[phases.setup]
nixPkgs = ["python313", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
