import type { Cluster } from "./types";
import { scoreCluster } from "./ai/score";

type SeedInput = Omit<Cluster, "score" | "rationale">;

const RAW: SeedInput[] = [
  // ── HIGH PRIORITY — safety-level issues ─────────────────────────────
  {
    id: "c-ward7-drainage",
    title: "Drainage repair, Ward 7",
    category: "sanitation",
    ward: "Ward 7",
    locality: "Subhash Nagar",
    affected: 340,
    urgency: "safety",
    status: "new",
    geo: { x: 62, y: 38 },
    relayShare: 0.42,
    sanctionedProject: "Community hall (most recent sanction, same area)",
    sampleQuotes: [
      "The drain near the school floods every monsoon, children wade through dirty water.",
      "नाली टूटी है, बारिश में घर के सामने पानी भर जाता है।",
      "Water logging for 3 days after rain, mosquitoes everywhere near the primary school.",
      "My children miss school every monsoon because the road becomes a river.",
    ],
  },
  {
    id: "c-ward9-health",
    title: "Sub-centre staffing & medicines, Ward 9",
    category: "health",
    ward: "Ward 9",
    locality: "Lakshmipur",
    affected: 210,
    urgency: "safety",
    status: "new",
    geo: { x: 46, y: 78 },
    relayShare: 0.55,
    sampleQuotes: [
      "The sub-centre has no doctor most days, we travel 20 km for fever.",
      "Pregnant women have no nearby checkup, this is a safety risk.",
      "उप-केन्द्र में दवाइयां नहीं हैं, डॉक्टर हफ्ते में एक बार आता है।",
      "Three women from our village had to deliver at home because the centre had no staff.",
    ],
  },

  // ── HIGH PRIORITY ─────────────────────────────────────────────────────
  {
    id: "c-ward3-school",
    title: "Upper-primary school upgrade, Ward 3",
    category: "education",
    ward: "Ward 3",
    locality: "Govindpura",
    affected: 184,
    urgency: "high",
    status: "forwarded",
    officeNote: "Forwarded to District Education Officer. Meeting scheduled for next month.",
    geo: { x: 28, y: 56 },
    relayShare: 0.52,
    sampleQuotes: [
      "Children walk 6 km to the nearest upper-primary school, many girls drop out.",
      "We need more classrooms and teachers, one room has three grades together.",
      "A vocational centre was proposed but the school itself has no science lab.",
      "बच्चों को 6 किलोमीटर पैदल जाना पड़ता है, बेटियां बीच में ही छोड़ देती हैं पढ़ाई।",
    ],
  },
  {
    id: "c-ward12-water",
    title: "Drinking water supply, Ward 12",
    category: "water",
    ward: "Ward 12",
    locality: "Rampur Khurd",
    affected: 156,
    urgency: "high",
    status: "forwarded",
    officeNote: "Forwarded to Jal Board. Follow-up raised in block meeting.",
    geo: { x: 78, y: 64 },
    relayShare: 0.30,
    sampleQuotes: [
      "Taps run dry by 9am, women queue at the single working borewell.",
      "Tanker comes twice a week, not enough for the whole colony.",
      "नल में पानी नहीं आता, हर सुबह दूर से पानी लाना पड़ता है।",
    ],
  },
  {
    id: "c-ward5-road",
    title: "All-weather road link, Ward 5",
    category: "roads",
    ward: "Ward 5",
    locality: "Bhimtal habitation",
    affected: 132,
    urgency: "high",
    status: "handling",
    officeNote: "Estimate sought from PWD; raised with district collector.",
    geo: { x: 18, y: 24 },
    relayShare: 0.61,
    sampleQuotes: [
      "Two hamlets are cut off when it rains, no ambulance can reach.",
      "The mud track turns to slush, school van refuses to come.",
      "बरसात में गांव कट जाता है, बीमार को कंधे पर उठाकर ले जाते हैं।",
      "PWD has surveyed the road three times but nothing happens.",
    ],
  },

  // ── MEDIUM PRIORITY ─────────────────────────────────────────────────
  {
    id: "c-ward14-power",
    title: "Evening power reliability, Ward 14",
    category: "electricity",
    ward: "Ward 14",
    locality: "Industrial colony",
    affected: 98,
    urgency: "normal",
    status: "info",
    officeNote: "Asked DISCOM for feeder load data before forwarding.",
    geo: { x: 84, y: 30 },
    relayShare: 0.12,
    sampleQuotes: [
      "Power cuts every evening when children study, voltage damages appliances.",
      "Transformer trips during peak hours, frequent outages.",
      "बच्चों की पढ़ाई का समय ही बिजली चली जाती है।",
    ],
  },
  {
    id: "c-ward7-streetlight",
    title: "Street lighting on school road, Ward 7",
    category: "electricity",
    ward: "Ward 7",
    locality: "Subhash Nagar",
    affected: 88,
    urgency: "high",
    status: "new",
    geo: { x: 66, y: 44 },
    relayShare: 0.21,
    sampleQuotes: [
      "No lights on the road girls take back from coaching, it feels unsafe.",
      "Dark stretch near the bus stop, accidents have happened.",
      "स्कूल जाने वाली लड़कियों के लिए रास्ता बहुत अंधेरा है।",
    ],
  },
  {
    id: "c-ward10-anganwadi",
    title: "Anganwadi centre renovation, Ward 10",
    category: "health",
    ward: "Ward 10",
    locality: "Nehru Nagar",
    affected: 74,
    urgency: "high",
    status: "new",
    geo: { x: 52, y: 42 },
    relayShare: 0.68,
    sampleQuotes: [
      "The anganwadi roof leaks, children sit in water during rain.",
      "No toilet in the centre, mothers take babies home early.",
      "आंगनवाड़ी की छत टपकती है, बच्चे बीमार पड़ते हैं।",
      "The weighing machine is broken, malnutrition tracking is not happening.",
    ],
  },
  {
    id: "c-ward6-road-repair",
    title: "Main road pothole repair, Ward 6",
    category: "roads",
    ward: "Ward 6",
    locality: "Market road junction",
    affected: 68,
    urgency: "normal",
    status: "handling",
    officeNote: "PWD work order issued, execution expected before monsoon.",
    geo: { x: 38, y: 35 },
    relayShare: 0.08,
    sampleQuotes: [
      "Three accidents this month due to potholes on the main market road.",
      "Two-wheelers fall daily near the junction, no lighting either.",
      "सड़क पर गड्ढे बहुत बड़े हो गए हैं, दुकानदार भी परेशान हैं।",
    ],
  },
  {
    id: "c-ward11-water-tank",
    title: "Overhead water tank, Ward 11",
    category: "water",
    ward: "Ward 11",
    locality: "New Extension",
    affected: 62,
    urgency: "high",
    status: "new",
    geo: { x: 72, y: 52 },
    relayShare: 0.35,
    sampleQuotes: [
      "New colony has 200 houses but no water infrastructure at all.",
      "We buy water from tankers at ₹300 per week, too expensive.",
      "नई कॉलोनी में पानी की कोई व्यवस्था नहीं है।",
    ],
  },
  {
    id: "c-ward13-school-toilet",
    title: "Girls' toilet block in primary school, Ward 13",
    category: "sanitation",
    ward: "Ward 13",
    locality: "Shivaji Nagar",
    affected: 56,
    urgency: "high",
    status: "forwarded",
    officeNote: "Escalated to BEO with female enrolment data.",
    geo: { x: 32, y: 70 },
    relayShare: 0.44,
    sampleQuotes: [
      "Girls drop out after class 5 because there is no girls' toilet.",
      "100 girl students share one broken toilet block.",
      "लड़कियों के लिए शौचालय नहीं है, पढ़ाई छूट जाती है।",
    ],
  },
  {
    id: "c-ward4-cremation",
    title: "Cremation ground boundary wall, Ward 4",
    category: "other",
    ward: "Ward 4",
    locality: "Hanuman Nagar",
    affected: 44,
    urgency: "normal",
    status: "new",
    geo: { x: 22, y: 62 },
    relayShare: 0.58,
    sampleQuotes: [
      "Animals enter the cremation ground at night, very disrespectful.",
      "No boundary wall means the site is used for illegal dumping.",
    ],
  },

  // ── PUBLISHED SHOWCASE ITEMS ─────────────────────────────────────────
  {
    id: "c-ward2-handpump",
    title: "Hand-pump restoration, Ward 2",
    category: "water",
    ward: "Ward 2",
    locality: "Nai Basti",
    affected: 210,
    urgency: "high",
    status: "published",
    outcome: "12 hand-pumps repaired and 3 new borewells commissioned — based on requests from 210 residents",
    publishedAt: "2026-05-18",
    geo: { x: 36, y: 18 },
    relayShare: 0.40,
    sampleQuotes: [
      "Now we get water in the morning without walking far.",
      "पहले 2 किलोमीटर जाना पड़ता था, अब गली में ही पानी है।",
    ],
  },
  {
    id: "c-ward8-toilets",
    title: "Community sanitation block, Ward 8",
    category: "sanitation",
    ward: "Ward 8",
    locality: "Market area",
    affected: 156,
    urgency: "normal",
    status: "published",
    outcome: "Two community sanitation complexes built and handed to the panchayat",
    publishedAt: "2026-04-02",
    geo: { x: 54, y: 58 },
    relayShare: 0.27,
    sampleQuotes: [
      "The market finally has clean toilets, women vendors are relieved.",
    ],
  },
  {
    id: "c-ward1-road",
    title: "Village access road, Ward 1",
    category: "roads",
    ward: "Ward 1",
    locality: "Adarsh Colony",
    affected: 320,
    urgency: "high",
    status: "published",
    outcome: "1.2 km all-weather road laid connecting Adarsh Colony to the main highway",
    publishedAt: "2026-03-15",
    geo: { x: 14, y: 44 },
    relayShare: 0.48,
    sampleQuotes: [
      "Finally ambulances can reach us in any weather.",
      "पक्की सड़क बन गई, बच्चे अब रोज स्कूल जा सकते हैं।",
    ],
  },
  {
    id: "c-ward15-solar",
    title: "Solar street lights installation, Ward 15",
    category: "electricity",
    ward: "Ward 15",
    locality: "Tribal hamlet",
    affected: 94,
    urgency: "high",
    status: "published",
    outcome: "28 solar street lights installed across 4 hamlets with no grid connectivity",
    publishedAt: "2026-02-20",
    geo: { x: 88, y: 72 },
    relayShare: 0.72,
    sampleQuotes: [
      "For the first time our hamlet has light at night.",
      "रात में बच्चे पढ़ सकते हैं, महिलाएं सुरक्षित हैं।",
    ],
  },
];

export function buildSeedClusters(): Cluster[] {
  return RAW.map((c) => {
    const { score, rationale } = scoreCluster(c);
    return { ...c, score, rationale };
  });
}
